import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL(".", import.meta.url));

// `server-only` throws by design outside a React Server Component. Every
// lib/server module imports it, so point it at the package's own no-op
// build instead of stubbing it per-test.
const alias = {
    "server-only": resolve(root, "node_modules/server-only/empty.js"),
    "@": root,
};

export default defineConfig({
    plugins: [react()],
    resolve: { alias },
    test: {
        globals: true,
        coverage: {
            provider: "v8",
            reportsDirectory: "./coverage",
            reporter: ["text-summary", "json-summary", "html"],
            include: ["lib/**/*.{ts,tsx}", "components/**/*.{ts,tsx}", "app/**/*.{ts,tsx}", "context/**/*.{ts,tsx}"],
            exclude: [
                "**/*.d.ts",
                "bench/**",
                "tests/**",
                // Thin barrels — a single `export * from "./service"` line with
                // no logic of their own. Listed explicitly rather than globbed:
                // several `index.ts` files (gateway, adapters, api-variants,
                // capabilities, db) are substantive and MUST stay measured.
                "lib/server/apikeys/index.ts",
                "lib/server/conversations/index.ts",
                "lib/server/logs/index.ts",
                "lib/server/mcp/index.ts",
                "lib/server/messages/index.ts",
                "lib/server/playground/index.ts",
                "lib/server/preferences/index.ts",
                "lib/server/stats/index.ts",
                "lib/server/tools/index.ts",
                "lib/server/users/index.ts",
                "lib/schemas/index.ts",
                // Side-effect-only registration barrels.
                "**/register.ts",
                // shadcn/ui primitives are vendored, regenerated by their CLI,
                // and exercised transitively by the components that use them.
                "components/ui/**",
            ],
            thresholds: {
                statements: 90,
                branches: 85,
                functions: 90,
                lines: 90,
            },
        },
        projects: [
            {
                extends: true,
                test: {
                    name: "node",
                    environment: "node",
                    include: ["tests/node/**/*.test.ts"],
                    setupFiles: ["./tests/setup/node.ts"],
                    benchmark: {
                        include: ["bench/**/*.bench.ts"],
                        exclude: ["bench/**/*.dom.bench.ts"],
                    },
                },
            },
            {
                extends: true,
                test: {
                    name: "dom",
                    environment: "jsdom",
                    include: ["tests/dom/**/*.test.{ts,tsx}"],
                    setupFiles: ["./tests/setup/dom.ts"],
                },
            },
        ],
    },
});
